[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["npx prisma generate"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
